project:
  type: website
  output-dir: docs
  
website:
  title: "Emily O'Neil's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - addtional_links.qmd
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full




